"""check users

Revision ID: 1cb8fe081d05
Revises: e6d29624e65a
Create Date: 2023-10-09 17:54:04.156101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb8fe081d05'
down_revision = 'e6d29624e65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
