"""???

Revision ID: 8d2356b221fa
Revises: 84e828e23ec4
Create Date: 2023-10-09 17:26:41.374116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2356b221fa'
down_revision = '84e828e23ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
