"""???

Revision ID: e6d29624e65a
Revises: 8d2356b221fa
Create Date: 2023-10-09 17:28:15.189042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d29624e65a'
down_revision = '8d2356b221fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
